eclipse-sprotty/sprotty

- src/lib/model.ts
- src/lib/svg-views.tsx
- src/utils/anchors.ts
- src/utils/geometry.ts
This change introduces a diamond node to the node library with proper anchoring of edges. Closes #2.
> Add diamond node

- src/features/move/move.ts
Signed-off-by: Jan Koehnlein <jan.koehnlein@typefox.io>
> [edit] delete edge in progress also if it wasn't dragged

- src/base/views/key-tool.ts
Fixes #30 by supporting 'keyup' event
Signed-off-by: Martin Fleck <mfleck@eclipsesource.com>
> #30: Support 'keyup' event in KeyTool

- src/features/update/update-model.ts
- src/graph/sgraph.ts
- src/utils/geometry.ts
> [edges] consider edges when calculating diagram bounds

- src/features/edge-layout/model.ts
This circular dependency slipped in with the edge layout commits.
> [build] avoid circular dependency

- src/features/viewport/center-fit.ts
> Fix zoom level computation in FitToScreenCommand (#39)

- css/sprotty.css
- examples/classdiagram/css/diagram.css
- src/graph/views.tsx
> #41 set radius of routing handles programmatically

- src/index.ts
Follow-up change for #33  that adds the  the tool-manager module to the index.ts file
> Add tool-manager module to index.ts

- package.json
> #49 make sprotty importable without 'lib'

- src/features/routing/di.config.ts
- src/features/routing/manhattan-anchors.ts
> [routing] elliptic and diamond anchors for manhattan routing

- src/model-source/commit-model.ts
- src/model-source/diagram-server.ts
- src/model-source/model-source.ts
> [model-source] allow to commit the model asynchonously

- src/base/actions/action-dispatcher.ts
- src/base/actions/diagram-locker.ts
- src/base/di.config.ts
- src/base/types.ts
- src/index.ts
> [edit] allow to block certain actions

- src/features/bounds/model.ts
- src/features/command-palette/command-palette.ts
This computation is available in the function `getAbsoluteClientBounds` which is now also used for computing the absolute position of the command palette.
Fixes #81
> Add more reliable absolute coordinates computation

- examples/classdiagram/src/di.config.ts
- src/base/types.ts
- src/features/move/move.ts
- src/features/move/snap.ts
- src/index.ts
> [ux] added a snap facility and a default grid aligmnent

- src/graph/sgraph-factory.ts
> [model] fixed wrong cast

- src/base/views/css-class-decorator.spec.tsx
> [decorator] added a test for css class decorator

- examples/circlegraph/src/di.config.ts
- examples/circlegraph/src/standalone.ts
- examples/classdiagram/src/di.config.ts
- examples/classdiagram/src/standalone.ts
- examples/mindmap/src/di.config.ts
- examples/mindmap/src/standalone.ts
- examples/multicore/src/di.config.ts
- examples/multicore/src/multicore.ts
- examples/svg/src/di.config.ts
- src/features/move/move.ts
- src/index.ts
- src/lib/modules.ts
Fixes #105.
I had to fix `LocationDecorator` because it was overriding the edge label positions computed by `EdgeLayoutDecorator` just by changing the order of modules.
> More convenient handling of default modules

- src/features/bounds/bounds-manipulation.ts
- src/features/bounds/bounds-manipulations.spec.ts
- src/features/bounds/hidden-bounds-updater.ts
- src/features/routing/model.ts
- src/model-source/di.config.ts
- src/model-source/diagram-server.ts
- src/model-source/local-model-source.spec.ts
- src/model-source/local-model-source.ts
- src/model-source/model-source.ts
> [bounds] only set size of server-side layouted elements

- src/base/features/set-model.ts
Needed to make the server example run
> [minor] allow full range of values in RequestModelActions.options

- src/base/views/vnode-utils.ts
- src/features/bounds/hidden-bounds-updater.ts
- src/lib/generic-views.ts
> Improved error message, extracted utility

- examples/classdiagram/css/diagram.css
- examples/classdiagram/src/di.config.ts
- examples/classdiagram/src/model-source.ts
- examples/classdiagram/src/views.tsx
- examples/classdiagram/tsconfig.json
- src/features/select/select.spec.ts
- src/features/select/select.ts
- src/features/zorder/di.config.ts
- src/features/zorder/zorder.spec.ts
- src/features/zorder/zorder.ts
- src/index.ts
- src/lib/modules.ts
Fixes #94.
In order to test this, I added a package node to the class diagram example. Click on the package and verify that the edge connected to the contained class stays on top. Without this change, the edge was overlaid by the package.
> Extracted z-order manipulation to BringToFrontCommand

- Jenkinsfile
Fix paths for yarn  "cache" and "global" directory by
- Updating the kubernetes config to ensure that the default directory for yarn-global is writable
- Updating the environmental variable for the cache folder path
> #154: Fix warnings in CI build

- src/features/update/update-model.ts
- src/model-source/local-model-source.ts
See https://github.com/eclipse/sprotty-server/pull/70 for server side pull request.
Signed-off-by: Soeren Domroes <sdo@informatik.uni-kiel.de>
> Added cause to UpdateModelAction

- src/features/context-menu/mouse-listener.ts
> Catch unavailable IContextMenuService

- package.json
> Align inversify dependency with Theia

- src/base/model/smodel.ts
- src/features/edge-layout/model.ts
- src/features/routing/model.ts
Fixed issues in Sprotty related to typescript 4
see: https://github.com/eclipse/sprotty/issues/218
> SPROTTY-77 fixed typscript 4 issues

- src/index.ts
https://github.com/eclipse/sprotty/issues/208
> Fix export of edge intersection module

- packages/sprotty/src/features/routing/bezier-edge-router.ts
- packages/sprotty/src/features/routing/di.config.ts
Implement review comments:
- Ensure the action is serializable
- Rename action and command
- Moved main execution code to command and removed unnecessary methods
Signed-off-by: Kai Salmen <kai.salmen@typefox.io>
> BezierEdgeRouter improvements

- packages/sprotty-elk/src/elk-layout.ts
Refactor usages of the `getBasicType` utility function in `ElkLayoutEngine` and related classes into protected methods. This makes it easier to overwrite the behavior in custom subclasses.
> #271 Improve extensibility of ElkLayoutEngine

- packages/sprotty/src/features/command-palette/command-palette.ts
Signed-off-by: Gabriel Dulca <victor.dulca@tuwien.ac.at>
> Fix command palette displaying spaces

- packages/sprotty/src/features/edge-layout/edge-layout.ts
> Corrected edge label placement for side='on'

- .vscode/launch.json
Updates outdated launch configs for mocha tests to correctly use `ts-mocha`
> Fix mocha launch configurations

- packages/sprotty/src/base/commands/command-stack.ts
- packages/sprotty/src/base/commands/command.ts
- packages/sprotty/src/features/move/move.ts
Addressed the issue mentioned [here](https://github.com/eclipse-sprotty/sprotty/pull/414#discussion_r1492263234).
> Improved stoppable command.

- packages/sprotty/src/features/viewport/zoom.ts
Using the suggested code from @BjBe82 , fixes #398
> Fix zoom jump bug

- packages/sprotty-protocol/src/actions.ts
- packages/sprotty/src/features/export/export.spec.ts
- packages/sprotty/src/features/export/export.ts
- packages/sprotty/src/features/export/svg-exporter.ts
- packages/sprotty/src/model-source/diagram-server.ts
- packages/sprotty/src/model-source/local-model-source.ts
- packages/sprotty/src/model-source/model-source.ts
The SVG export related actions can be useful in server applications.
> Extract SVG export actions to sprotty-protocol

- examples/browser-app.ts
- examples/index.html
- examples/styling-showcase/README.md
- examples/styling-showcase/css/diagram.css
- examples/styling-showcase/css/page.css
- examples/styling-showcase/src/di.config.ts
- examples/styling-showcase/src/standalone.ts
- examples/styling-showcase/src/views.tsx
- examples/styling-showcase/styling-showcase.html
In an effort to improve our documentation, I am planning to add examples that are in direct relation with parts of the documentation.
Here is the first of such examples that illustrates what is described in the [Styling Recipe](https://sprotty.org/docs/recipes/styling/)
> Add styling example
