src/base/actions/action-dispatcher.ts
The IActionDispatcherProvider type has been missing, however, it is available in the DI container. Thus, to make it easier for clients to obtain the action dispatcher via a provider, this change adds and exports the corresponding type.
=> Add IActionDispatcherProvider type

src/base/views/mouse-tool.ts, src/features/open/open.ts
MouseEvents: corrected doubleClick to be a MouseEvent
Signed-off-by: Niklas Rentz <nre@informatik.uni-kiel.de>
=> MouseEvents: corrected doubleClick to be a MouseEvent

css/command-palette.css, examples/classdiagram/src/di.config.ts, examples/classdiagram/src/model.ts, package.json, src/base/di.config.ts, src/base/types.ts, src/base/ui-extensions/ui-extension-registry.ts, src/base/ui-extensions/ui-extension.ts, src/features/command-palette/action-providers.ts, src/features/command-palette/command-palette.ts, src/features/command-palette/di.config.ts, src/features/nameable/model.ts, src/index.ts, yarn.lock
Introduces an extensible command palette as a keyboard-oriented way of invoking actions similar to a Code Completion / IntelliSense / Quick-Fix functionality for code. The available commands are determined by registered action providers that provide a set of `LabeledAction`s for a context. A `LabeledAction` is essentially a label to be shown in the list and an array of Sprotty `Action`s to be dispatched on invocation.
The command palette is shown on <kbd>Ctrl</kbd> + <kbd>Space</kbd>. If there is no selection or multi-selection, it shows up in the left-upper corner of the base div. If there is a single selection, it is shown on top of the selected element.
The command palette is built on top of a UI extension mechanism introduced with this PR as well to register UI extensions. UI …
=> Add support for a command palette (#34)

src/features/command-palette/command-palette.ts
=> Hide command palette when Escape key pressed

css/edit-label.css, examples/classdiagram/class-diagram.html, examples/classdiagram/src/di.config.ts, examples/classdiagram/src/label-validation.ts, examples/classdiagram/src/label-validator.ts, examples/classdiagram/src/model-source.ts, examples/classdiagram/src/model.ts, src/base/types.ts, src/base/ui-extensions/ui-extension-registry.ts, src/base/ui-extensions/ui-extension.ts, src/features/command-palette/command-palette.ts, src/features/edit/di.config.ts, src/features/edit/edit-label-ui.ts, src/features/edit/edit-label.ts, src/features/edit/model.ts, src/features/viewport/zoom.ts, src/index.ts
This change introduces a user interface -- as discussed in #83 -- for editing labels.
The UI for label editing is hooked up in the optional `labelEditUiModule` which reacts to the existing `EditLabelAction` and then provides a UI based on the `UIExtension` mechanism introduced a while ago. When the user confirms the edit, the UI extension sends out an `ApplyLabelEditAction`, which should be handled by a command actually updating the model. The default command just updates the text of the `EditableLabel`. In other use cases, such as GLSP or LSP driven diagrams, a different command could be bound that delegates performing the actual update to the respective server.
I tried to leave as much as possible in terms of styling to the CSS. However, the UI extension tries to obtain the label's font …
=> Add user interface for label editing (#83)

css/command-palette.css, examples/classdiagram/class-diagram.html, src/base/di.config.ts, src/base/views/mouse-tool.ts, src/features/command-palette/action-providers.ts, src/features/command-palette/command-palette.ts
This additional info includes the last known mouse position on the
diagram as well as the text entered into the command palette so far.
This additional info is helpful to allow for more sophisticated
and context sensitive suggestions and ordering of those suggestions.
Moreover, this change makes it easier to override the behavior for
fetching the command palette actions on typing, introduces a debounce
delay to avoid flooding the action providers with requests on each
keystroke, and finally, it adds a HTML class to the input element
while loading actions to allow visually showing that actions are
currently being loaded.
=> Enhance context information for command palette action providers

examples/circlegraph/src/di.config.ts, examples/classdiagram/src/di.config.ts, examples/classdiagram/src/model.ts, examples/mindmap/src/di.config.ts, examples/mindmap/src/model.ts, examples/multicore/src/chipmodel-factory.ts, examples/multicore/src/chipmodel.ts, src/base/model/smodel-factory.spec.ts, src/base/model/smodel-factory.ts, src/base/model/smodel-utils.ts, src/base/model/smodel.ts, src/base/views/view.tsx, src/features/bounds/hbox-layout.spec.ts, src/features/bounds/stack-layout.spec.ts, src/features/bounds/vbox-layout.spec.ts, src/features/button/model.ts, src/features/decoration/model.ts, src/features/routing/model.ts, src/features/viewport/viewport-root.ts, src/graph/sgraph-factory.ts, src/graph/sgraph.ts, src/lib/model.ts, src/utils/registry.ts
Fixes #104. I chose a solution that operates in the registry for model elements, not in the factory or the element constructors, because I wanted to make sure that all instances of an element type hold a reference to the same feature set, to avoid unnecessarily high memory usage.
=> Added parameter to specify CustomFeatures in configureModelElement

src/features/viewport/center-fit.ts
This was breaking all other zoom features, if some initial model that was drawn had zero size and therefore infinite zoom. With this, it just defaults back to a zoom level of 1.
Signed-off-by: Niklas Rentz <nre@informatik.uni-kiel.de>
=> viewport: Fixed FitToScreenCommand from zooming to Infinity

src/base/views/viewer.tsx, src/features/viewport/zoom.ts, src/utils/browser.ts
Fixes #114.
* Take into account the `deltaMode` of the WheelEvent.
* Use `clientX` / `clientY` instead of the unreliable `offsetX` / `offsetY`
=> Fixed zooming for Firefox

src/features/viewport/center-fit.ts
When centering, you don't always want the zoom level to be reset.
Needs [this](https://github.com/eclipse/sprotty-server/pull/58) as well
=> Allowed the CenterAction to retain the zoom level

src/features/command-palette/action-providers.ts, src/features/command-palette/command-palette.ts
Fixes #140 
For illustration purposes, I integrated this -- as usual -- into the class diagram example (below I pushed <kbd>Ctrl+Space</kbd> multiple times).
=> Support for cycling through command palettes (#140)

src/base/views/vnode-postprocessor.ts, src/graph/views.spec.tsx
Use tabindex 0 (automatically add it to the sequential tab order) for SVG element.
Tabindex has to be set in order to allow focus on FireFox
=> [view] use tabindex 0 for svg element

Jenkinsfile, src/features/command-palette/command-palette.ts
This change simplifies showing a loading indicator while the
command palette is loading actions, e.g. with fontawesome.
It is now easy to just override loadingIndicatorClasses, which
will be assigned to a span element after the command palette
input. With CSS and fontawesome, clients can then show a
spinning icon while the actions are loading with plain css.
=> Improve loading indicator of command palette

src/features/command-palette/command-palette.ts
If for some reason the update of items fails and we never get to removing
the loading indicator, we have to avoid re-adding another one the
next time we show the command palette. Otherwise we may end up with
a remaining loading indicator that is never removed.
Also this change makes the onSelect customizable by subclasses.
=> Avoid adding duplicate loading indicators in command palette

src/features/hover/hover.spec.ts, src/features/hover/hover.ts
With this change, I suggest to always reset the hover feedback of the previous element on mouseover of any diagram element. This ensures that we reset the hover feedback also if the user exited the element without producing any mouseout event of the original hovered element.
Resolves #152
=> Reset previous hover feedback on mouseover

src/features/context-menu/context-menu-service.ts, src/features/context-menu/menu-providers.ts
Also remove Promise<boolean> from the allowed return types in
`MenuItem`, since this may cause issues for `ContextMenuServiceProvider`
that can't handle a promise as they need to return synchonosly.
This is for instance true for the Theia CommandHandler in sprotty-theia:
src/sprotty/theia-sprotty-context-menu-service.ts#L117
=> Rename context menu provider for delete

src/base/features/initialize-canvas.ts, src/features/bounds/model.ts, src/features/hover/popup-position-updater.ts, src/utils/browser.ts
Use of window.pageXOffset instead of window.scrollX  (same for Y) to support all browsers.
https://github.com/eclipse/sprotty/wiki/Browsers-and-Compatibility was updated accordingly
=> #162: IE11-compatible window scroll retrieval

css/edit-label.css, examples/svg/css/diagram.css, examples/svg/src/di.config.ts, examples/svg/src/standalone.ts, examples/svg/svg-prerendered.html, src/base/ui-extensions/ui-extension-registry.ts, src/base/ui-extensions/ui-extension.ts, src/features/command-palette/command-palette.ts, src/features/edit/edit-label-ui.ts, src/features/edit/model.ts, src/lib/generic-views.tsx, src/lib/model.ts
https://github.com/eclipse/sprotty/issues/169
=> Add support for foreignObject and enhance label editing with multi-line support

src/features/edit/edit-label-ui.ts
We always add the event listener for label validation to the input element
but not to the text area. For the label edit validation to work, we need to
also add an event listener to the text area (ie the element that is passed
as argument in configureAndAdd(...).
=> Fix label validation if edit control is text area

src/features/edit/edit-label-ui.ts
This change also prevents the default behavior if the configured key
combination for submitting the label edit has been pushed. This allows
also using keys that would modify the input/textarea content.
=> Always confirm label edit on enter

src/features/fade/fade.ts, src/features/move/move.ts
This change omits `transform` attributes generated by LocationPostprocessor when they have no effect (x and y are zero), and it omits `opacity` attributes generated by ElementFader when they have no effect (opacity is 1).
=> Omit 'transform' and 'opacity' when they have no effect

examples/multicore/src/chipmodel.ts, src/base/actions/action-dispatcher.spec.ts, src/base/actions/action-dispatcher.ts, src/base/actions/action.ts, src/base/features/set-model.ts, src/base/views/mouse-tool.ts, src/features/bounds/abstract-layout.ts, src/index.ts, src/utils/json.ts
It should be possible to reject request actions. This change introduces RejectAction for this purpose.
This is particularly important for requests that are forwarded to a diagram server, e.g. RequestModelAction. We should implement the new feature in sprotty-server, too, after this is merged.
=> Added ability to reject request actions

.gitpod.yml, examples/circlegraph/css/diagram.css, examples/circlegraph/src/di.config.ts, examples/circlegraph/src/standalone.ts, examples/circlegraph/src/views.tsx, examples/classdiagram/src/views.tsx, examples/multicore/src/views.tsx, src/base/di.config.ts, src/base/views/thunk-view.spec.tsx, src/base/views/view.spec.ts, src/base/views/view.tsx, src/base/views/viewer.tsx, src/features/bounds/model.spec.ts, src/features/bounds/model.ts, src/features/bounds/views.spec.ts, src/features/bounds/views.ts, src/features/routing/model.spec.ts, src/features/routing/model.ts, src/features/routing/views.spec.ts, src/features/routing/views.ts, src/graph/views.spec.tsx, src/graph/views.tsx, src/index.ts, src/lib/generic-views.tsx, src/lib/svg-views.tsx
This change allows views to return `undefined` instead of a VNode and adds utility functions to check whether elements are visible in the current viewport. This enables to completely skip elements that are outside of the viewport, which can greatly enhance performance.
The changes should have no effect on existing applications, but they can opt in to use the new code to improve responsiveness.
I used this code in the Circlegraph and the Multicore examples. The effect can be seen best when the initial number of nodes of the Circlegraph example is set to 8000 (`examples/circlegraph/src/standalone.ts` line 73). The view is quite unresponsive, but it gets a lot better if you pan to the side so only a part of the nodes and edges are visible.
=> Allow to skip rendering invisible elements

package.json, src/base/model/smodel.spec.ts, src/base/model/smodel.ts, yarn.lock
This is a preparation for eclipse/sprotty-layout#12. There are situations where one needs a reference to a parent element, which is not available in SModelElementSchema. The new code does not add any memory overhead for the internal model (SChildElement already has a `parent` property).
=> Added getParent and getRoot to SModelIndex

Jenkinsfile
This triggers the "deploy-sprotty" Jenkins job for every change on the master.
Note: Before merging this PR the current deployment Jobs running on the Typefox CI should be deactivated to avoid conflicts.
=> #150 Add stage for deploying npm next artifacts to Jenkinsfile

src/features/move/move.ts, yarn.lock
Fixes #195
After the first `mouseDown` event on an text element, firefox always triggers a `mouseEnter` event as well (other browsers don't).
This will undo the state changes made by the `mouseDown` event. 
To fix this, we will simply check on `mouseEnter` whether the element is already in a dragging state before we call `mouseUp`.
=> Text element dragging fix for firefox

package.json, yarn.lock
Fixes #198
Some version of ecstatic (dependency of http-server) introduced redirection issues under windows, as discussed in here https://github.com/http-party/http-server/issues/525.
Updating the dependency resolves this issues.
=> Fixing examples redirection issue

src/features/move/move.ts
Fixes #161 
While selecting the elements to move, we ignore those whose parents are already selected.
I also took the freedom to apply a formatter on the whole `move.ts` file.
=> Only move element if parent is not moving

src/features/update/update-model.spec.ts, src/features/update/update-model.ts
Hi,
I intentionally moved the test to the end of the mocha spec because I had the impression that there exists the risk of mutating the model context in an undesired way. Is it okay or should the test be isolated by creating a vanilla context using a new describe() method?
Thx!
=> Fix #190: Duplicate ID in model error during update if parent is changed

src/base/model/smodel-utils.ts, src/features/update/update-model.spec.ts, src/features/update/update-model.ts
…by only fading out nodes if none of the children is present in the new root.
Towards #190 (needs to be re-tested)
Signed-off-by: Daniel Dietrich <daniel.dietrich@typefox.io>
=> Fixes duplicate ID errors

src/features/undo-redo/undo-redo.ts
Consider Ctrl+Y as redo keyboard shortcut.
Browsers usually support both Ctrl+Y and Ctrl+Shift+Z in e.g., input elements.
=> Redo with CrtlCmd+Y

configs/.eslintrc.js, src/base/actions/action.ts, src/base/commands/command-stack-options.ts, src/base/views/viewer-options.ts, src/base/views/vnode-utils.ts, src/features/select/select.ts, src/features/update/model-matching.ts, src/model-source/diagram-server.ts, src/utils/inversify.ts, src/utils/object.ts
Eslint warns calling the hasOwnProperty method directly from object.
Where we can do without hasOwnProperty, I remove it, and use the own functions if needed.
Also, added type guard so that "as any" does not have to be used.
=> Enabled eslint rule "no-prototype-builtins".

src/base/types.ts, src/features/bounds/abstract-layout.ts, src/features/bounds/di.config.ts, src/features/bounds/hbox-layout.spec.ts, src/features/bounds/hbox-layout.ts, src/features/bounds/layout.ts, src/features/bounds/stack-layout.spec.ts, src/features/bounds/stack-layout.ts, src/features/bounds/vbox-layout.spec.ts, src/features/bounds/vbox-layout.ts
Modify the LayoutRegistry to support LayoutRegistrations via dependency-injection, similar to how it's done for other registries
=> Add dependency-injection support to LayoutRegistry

css/sprotty.css, examples/svg/css/diagram.css, examples/svg/css/page.css, examples/svg/src/di.config.ts, examples/svg/src/standalone.ts, src/base/actions/action-handler.ts, src/base/views/mouse-tool.ts, src/base/views/view.tsx, src/base/views/viewer.tsx, src/features/bounds/views.ts, src/features/move/move.ts, src/features/projection/model.ts, src/features/projection/views.tsx, src/features/viewport/scroll.ts, src/features/viewport/viewport-root.ts, src/index.ts, src/lib/html-views.tsx, src/utils/browser.ts
This PR adds "projection bars". These are similar to the scrollbars in IDEs like Eclipse and VS Code, where you have colored markers at interesting code regions like errors or SCM changes. The difference is that they can appear in two dimensions, so you can have a horizontal and a vertical projection.
Projection bars are added by using `ProjectedViewportView` as view of the root element and configuring marker colors for some model elements. This can be either dynamic by implementing `getProjection` (for example to show only elements with certain properties) or static with the following pattern in the diagram configuration:
```typescript
configureModelElement(context, 'pre-logo', ShapedPreRenderedElement, PreRenderedView, {
viewInit: setProjection('rgba(255, 153, 0, 0.5)')
});
```
An …
=> Implemented projection on horizontal and vertical bars

examples/classdiagram/class-diagram.html, examples/classdiagram/css/diagram.css, examples/classdiagram/src/di.config.ts, examples/classdiagram/src/model-source.ts, src/features/routing/abstract-edge-router.ts, src/features/routing/bezier-anchors.ts, src/features/routing/bezier-edge-router.ts, src/features/routing/di.config.ts, src/features/routing/linear-edge-router.ts, src/features/routing/manhattan-edge-router.ts, src/features/routing/model.ts, src/features/routing/polyline-edge-router.ts, src/features/routing/routing.ts, src/graph/views.tsx, src/index.ts
This PR introduces preliminary support for cubic Bézier curve edges.
What has been achieved:
Issues that should be fixed before PR is ready
What is still missing (reason for being preliminary). To be discussed if done in scope of this PR or later:
The classdiagram has been enhanced to show the new capabilities.
=> Add preliminary support for Cubic Bézier curve edge

.gitignore, examples/random-graph/src/di.config.ts, packages/sprotty-elk/CHANGELOG.md, packages/sprotty-elk/src/elk-layout.spec.ts, packages/sprotty-elk/src/elk-layout.ts, packages/sprotty-elk/src/index.ts, packages/sprotty-elk/src/inversify.ts, packages/sprotty-protocol/src/diagram-server.spec.ts, packages/sprotty-protocol/src/diagram-server.ts, packages/sprotty-protocol/src/diagram-services.ts, packages/sprotty-protocol/src/index.ts
This PR improves a few aspects of the new `DiagramServer`:
* Extracted service definitions to a separate file
* Made `state` public
* Made `layoutEngine` optional
* LayoutAction is executed regardless of the `needServerLayout` option
It also refines the content of the recently copied `sprotty-elk` package:
* Separated plain definitions and InversifyJS specific definitions
=> Improved diagram server API

configs/.eslintrc.js, packages/sprotty-protocol/CHANGELOG.md, packages/sprotty-protocol/src/action-handler.ts, packages/sprotty-protocol/src/diagram-server.spec.ts, packages/sprotty-protocol/src/diagram-server.ts, packages/sprotty-protocol/src/diagram-services.ts
In my first draft of the diagram server, I included the option to register action handlers so it's not necessary to subclass `DiagramServer` just to process incoming actions. But `DiagramServer` instances must be created per client diagram, so there can be possibly many such instances in the backend. I think it would be more convenient to register the action handlers in a separate service instead of the `DiagramServer` instances.
=> Extracted action handler registry from diagram server

packages/sprotty/src/features/hover/hover.spec.ts, packages/sprotty/src/features/hover/hover.ts
Remove the hover feedback from the last hover feedback element also
if the mouse-out event occurs for another element. This is needed e.g.
when an edge is entered with the mouse where the routing handle would
appear on selection and then left via the routing handle.
Fixes https://github.com/eclipse/sprotty/issues/264
=> Remove hover feedback for last element

.eslintrc.js, .vscode/settings.json, Jenkinsfile, configs/base.tsconfig.json, examples/webpack.config.js, lerna.json, package.json, packages/sprotty-elk/package.json, packages/sprotty-protocol/package.json, packages/sprotty/package.json, tsconfig.json
Setup nightly deployment for new mono repo
- Add dedicated scripts for publishing  releases (publish:latest) and nightly snapshots (publish:nightly) using lerna
- Update lerna config
[CI]
- Updated `deploy-sprotty` jenkins job
Additional changes:
- Update eslint config. After the mono-repo switch the config was no longer working with the eslint vscode extension. Added a new root .eslint.rc + tsconfig.json to fix that.
- Ignore warnings related to source map parsing in the example webpack config
- Add schema property to `base.tsconfig.json`
Closes #261
=> #261 Setup nightly deployment

packages/sprotty-elk/src/elk-layout.ts, packages/sprotty-protocol/src/actions.ts, packages/sprotty/src/base/features/set-model.ts, packages/sprotty/src/features/bounds/bounds-manipulation.ts, packages/sprotty/src/features/edit/edit-label-ui.ts, packages/sprotty/src/features/edit/edit-label.ts, packages/sprotty/src/features/expand/expand.ts, packages/sprotty/src/features/hover/hover.ts, packages/sprotty/src/features/open/open.ts, packages/sprotty/src/features/select/select.ts, packages/sprotty/src/features/update/update-model.ts, packages/sprotty/src/features/viewport/center-fit.ts, packages/sprotty/src/features/viewport/viewport.ts, packages/sprotty/src/model-source/diagram-server.ts
- Ensures that the new action definitions of `sprotty-protocol` are used consistently over the deprecated class-based definition.
- Ensure that all commands with injected actions use the sprotty-protocol type instead of its deprecated counterpart
- Update deprecated action class definitions so that the also implement the corresponding interface from `sprotty-protocol`. This ensures that the deprecated definitions are compatible on a type level with the new protocol actions. To avoid name clashings the protocol actions are imported with a `Protocol` prefix.
- Also: fix some ESLint warnings
This also fixes problems when extending one of the command classes provided by sprotty.
For instance with the current master state it would not be possible to extend the `UpdateModelCommand` and use
the …
=> Ensure consistent usage of protocol actions

.vscode/launch.json, examples/.gitignore, examples/browser-app.ts, examples/index.html, examples/package.json, examples/random-graph-distributed/css/diagram.css, examples/random-graph-distributed/css/page.css, examples/random-graph-distributed/random-graph.html, examples/random-graph-distributed/src/di.config.ts, examples/random-graph-distributed/src/http-model-source.ts, examples/random-graph-distributed/src/standalone.ts, examples/server/random-graph-generator.ts, examples/server/server-app.ts, examples/tsconfig.json, examples/webpack.config.js, packages/sprotty-elk/package.json, packages/sprotty-elk/src/elk-layout.ts, packages/sprotty-elk/src/node/index.ts, packages/sprotty-elk/src/node/layout-data.ts, packages/sprotty-elk/src/node/socket-server.ts, packages/sprotty-elk/src/node/stdio-server.ts, packages/sprotty-elk/tsconfig.json, yarn.lock
This PR adds two classes `SocketElkServer` and `StdioElkServer` to `sprotty-elk` that enable to run the ELK layout engine in a separate Java process. The Java application is implemented in a new MIT-licensed project [elk-server](https://github.com/TypeFox/elk-server).
1. Download [elk-server](https://github.com/TypeFox/elk-server/releases/tag/v0.1.0)
2. Run the application with the `--socket` argument:
```
elk-server-0.1.0/bin/elk-server --socket
```
3. Build and run the examples server (`yarn start`)
4. Open the new "random graph" example in the "With Server" section on http://localhost:8080/
The result should look similar to the previous in-browser "random graph" example.
=> Implemented client for running ELK layout in a separate process

package.json
Remove --canary tag to ensure that the version for next publishes is correctly set to <last_release+minor> i.e. to 0.12.0-next....
=> Update publish:next script

.vscode/launch.json, examples/random-graph/src/di.config.ts, packages/sprotty/src/features/edge-intersection/intersection-finder.ts, packages/sprotty/src/graph/views.tsx, packages/sprotty/src/utils/geometry.spec.ts, packages/sprotty/src/utils/geometry.ts
Also...
* Fixes launch config for running single tests
* Adds line gaps to random-graph example for testing
* Mention that intersection finder only works for straight segments (#287)
I've added line gaps to the random-graph example to simplify verifying whether all intersections are correctly marked.
So I suggest to use that for verifying whether it works now:
https://user-images.githubusercontent.com/588090/167085594-6e062fff-fb10-4d0f-aefd-90e63606f41a.mp4
Fixes #277
Change-Id: I3c72de91188e32fcb296ef81f27c6b03e18c8bd0
=> Fix edge views that consider intersections

packages/sprotty-elk/package.json, packages/sprotty/package.json
Using ^5.0.1 currently pulls 5.1.1 wich is not compatible with 5.0.1 pulled by the downstream projects. Affect e.g. sprotty-vscode, sprotty-elk
=> Use more strict inversify version

packages/sprotty/src/base/views/mouse-tool.ts, packages/sprotty/src/features/context-menu/mouse-listener.ts
Fixes https://github.com/eclipse/sprotty/issues/294
Change-Id: Ia075d491a4d4ed6917e8e6ea45e982f61916773f
=> Support `contextmenu` event in mouse tool

packages/sprotty/src/base/views/mouse-tool.ts, packages/sprotty/src/features/projection/views.tsx
Enables focus for the root `div` element 
Fix  #299
=> No Key events when using Projections

packages/sprotty/src/base/types.ts, packages/sprotty/src/features/button/button-handler.ts, packages/sprotty/src/features/expand/di.config.ts
With the current bindings it is not possible to inject into a ButtonHandler.
The registry now recieves a factory instead of a constructor.
Also provide helper method to bin new ButtonHandlers.
Resolves #300
Contributed on behalf of STMicroelectronics
=> Rework ButtonHandler registration

examples/classdiagram/src/di.config.ts, packages/sprotty/src/base/di.config.ts, packages/sprotty/src/features/command-palette/di.config.ts, packages/sprotty/src/features/context-menu/di.config.ts, packages/sprotty/src/features/edit/di.config.ts, packages/sprotty/src/features/export/di.config.ts, packages/sprotty/src/features/hover/di.config.ts, packages/sprotty/src/features/move/di.config.ts, packages/sprotty/src/features/open/di.config.ts, packages/sprotty/src/features/select/di.config.ts, packages/sprotty/src/features/undo-redo/di.config.ts, packages/sprotty/src/features/viewport/di.config.ts
Make it simpler to extend existing mouse and key listeners.
=> Use service binding for all Mouse and KeyListeners

.vscode/launch.json, configs/.mocharc.json, examples/circlegraph/circlegraph.html, examples/circlegraph/css/page.css, examples/circlegraph/src/di.config.ts, examples/circlegraph/src/standalone.ts, packages/sprotty/src/base/views/mouse-tool.ts, packages/sprotty/src/graph/views.spec.tsx
Adds two new even types `dragover` and `drop`. 
Enhanced the Circle example to demonstrate the  drag and drop functionality.
Try it out by dragging the 'drag' circle into the Graph:
Also added a new launch config to run all the tests.
=> Makes it possible to listen to mouse drop events

examples/classdiagram/src/di.config.ts, examples/package.json, examples/webpack.config.js, packages/sprotty/CHANGELOG.md, packages/sprotty/package.json, packages/sprotty/src/features/command-palette/di.config.ts, yarn.lock
- This removes the need to have codicon as depedency to the sprotty core
- Replace rimraf wih shx along the way
This is the proposed solution for #311
=> Remove codicon.css, document and explain future usage

examples/circlegraph/src/standalone.ts
At this point, the point argument must be optional because the `createContainer` function requires it, and the `addNode` event handler actually calls this function later without arguments.
=> Small optional type fix in circlegraph example

packages/sprotty-protocol/src/actions.ts, packages/sprotty/src/base/actions/action-dispatcher.ts, packages/sprotty/src/features/button/button-handler.ts, packages/sprotty/src/features/context-menu/menu-providers.ts, packages/sprotty/src/features/edit/create.ts, packages/sprotty/src/features/edit/delete.ts, packages/sprotty/src/features/edit/edit-label-ui.ts, packages/sprotty/src/features/edit/edit-label.ts, packages/sprotty/src/features/edit/reconnect.ts, packages/sprotty/src/features/hover/hover.ts, packages/sprotty/src/features/move/move.ts, packages/sprotty/src/features/select/select.ts, packages/sprotty/src/features/undo-redo/undo-redo.ts, packages/sprotty/src/features/zorder/zorder.ts, packages/sprotty/src/model-source/logging.ts
I extracted lots of functionality to protected methods to structure the code better and to enable fine-grained customization. Those two mouse listeners carry a lot of the interaction logic, which is not optimal.
Moving the action definitions to the sprotty-protocol package enables accessing them in Node.js based servers.
=> API improvements

packages/sprotty/src/features/edit/edit-label-ui.ts
This problem was observed in [GLSP](https://github.com/eclipse-glsp/glsp/issues/766) as sending an "empty" operation still makes the editor dirty due to a command being on the command stack.
=> Avoid sending label edit action if there is no change

.gitpod.yml, .vscode/launch.json, packages/sprotty-elk/src/node/layout-data.ts, packages/sprotty-elk/src/node/stdio-server.ts
When the ELK server is invoked with a graph that does not have any layout information, the edge routes were not applied. This PR fixes that bug.
=> Fixed edge layout when there are no routing points yet

packages/sprotty/src/features/move/move.ts
Fixes ` Error: Duplicate ID in model: edge0_dangling-source`, see #335
How to test: Open the Class diagram example. You should be able to reconnect edges more than once.
=> Reconnecting of edges breaks dragging #335

packages/sprotty/src/features/routing/manhattan-edge-router.ts
Allows moving single routing point with Manhattan routing, see #310
=> Move single routing point with Manhattan #310

packages/sprotty/src/features/viewport/zoom.ts
To try it out open the SVG example, hold `alt` and use mouse wheel or touchpad to scroll.
See #339
=> Allows scrolling the viewport using alt + wheel

packages/sprotty/src/features/select/select.ts, packages/sprotty/src/features/viewport/scroll.ts
- Prevents losing selection when panning with the mouse
- Single click on model root still deselects all elements.
- Also fixes the selection los when using scroll bars #302  
How to verify:
- select one or more elements in an example project
- pan with the mouse - selection should remain the same
- click the root area - selection should be reseted
=> Don't lose selection when clicking over root

packages/sprotty/src/base/actions/action-handler.ts, packages/sprotty/src/base/actions/action.ts, packages/sprotty/src/base/features/set-model.ts, packages/sprotty/src/base/model/smodel.ts, packages/sprotty/src/base/ui-extensions/ui-extension.ts, packages/sprotty/src/features/bounds/bounds-manipulation.ts, packages/sprotty/src/features/button/model.ts, packages/sprotty/src/features/edit/create.ts, packages/sprotty/src/features/edit/delete.ts, packages/sprotty/src/features/edit/edit-label.ts, packages/sprotty/src/features/edit/reconnect.ts, packages/sprotty/src/features/hover/hover.ts, packages/sprotty/src/features/move/move.ts, packages/sprotty/src/features/select/select.ts, packages/sprotty/src/features/undo-redo/undo-redo.ts, packages/sprotty/src/features/viewport/center-fit.ts, packages/sprotty/src/features/viewport/model.ts, packages/sprotty/src/features/zorder/zorder.ts, packages/sprotty/src/model-source/diagram-server.ts, packages/sprotty/src/model-source/local-model-source.ts, packages/sprotty/src/model-source/logging.ts, packages/sprotty/src/utils/geometry.ts
Ensure that deprecated types are isolated and don't leak into non-deprecated  definitions. => Consistently use definitions from sprotty protocol in non-deprecated  classes,functions or type definitions.
=> Cleanup deprecated types

packages/sprotty-elk/src/node/socket-server.ts
When running the random graph generator example, I see an error like:
I noticed the host name looked odd. I found [this SO post](https://stackoverflow.com/questions/10643965/econnrefused-error-with-node-js-that-does-not-occur-in-other-clients) and [this SO post](https://stackoverflow.com/questions/73843720/connect-econnrefused-127017) that explain that node has issues with `localhost` and to use `127.0.0.1` instead. So, I made this change locally to the socket connect call and it fixed the issue:
=> specify host as 127.0.0.1

packages/sprotty-protocol/src/actions.ts, packages/sprotty/src/features/viewport/center-fit.ts
Added a `zoomScale` property to the `CenterAction` to explicitly set te zoom level when centering the view.
**how to test**
in the circlegraph example:
- add following new button to the `circlegraph.html` file
``` <button id="centerZoomed">center and zoom selection</button>```
-  add following code to the `standalone.ts` to execute the center action on click
```    
document.getElementById('centerZoomed')!.addEventListener('click', async () => {
dispatcher.dispatch(CenterAction.create(graph.children.map(el => el.id), {animate: true, zoomScale: 2}))
});
```
now when clicking the button the center action is executed and zoom level is set to 2.
=> added zoomScale property to centerAction to set zoom level when executing the action

examples/circlegraph/src/di.config.ts, examples/classdiagram/src/di.config.ts, packages/sprotty/src/features/export/di.config.ts, packages/sprotty/src/features/fade/di.config.ts, packages/sprotty/src/features/hover/di.config.ts, packages/sprotty/src/features/routing/di.config.ts
Double check the codebase and ensure that all all multi-injected classes are bound to self() in Singleton scope before binding them to the multi injection key 
Fixes #239
=> Improve extensibility of multi-injected keys

examples/classdiagram/class-diagram.html, examples/classdiagram/css/diagram.css, examples/classdiagram/src/di.config.ts, examples/classdiagram/src/menu.ts, packages/sprotty/src/features/context-menu/mouse-listener.ts
As in a lot of cases the target element must not be selectable I removed the if condition from `menu-listener.ts`.
- In case of a non selectable element the next selectable parent will be checked.
- In case of root (normally not selectable) the menu will be shown too
I also added a context menu to our class diagram example so we can discuss the current selection behavior.
Please note that a lot of actions act on elements that they retrieve from the available selection tracking services (e.g. GetSelectionAction or LocalModelSource.getSelection).
=> Allow context menu on not selectable elements #345

.vscode/tasks.json, packages/sprotty/src/features/edit/edit-label-ui.ts
If the font size property is a number with decimals, the regular expression didn't account for the decimal place. This change enhances the regular expression to match also the numbers after the decimal point.
Initially raised in https://github.com/eclipse-sprotty/sprotty/pull/351
Also this change fixes the VS Code build task of this repository.
Change-Id: I9592518e533e5636e4f3a27319cbe96a5ec71ae1
=> Fix font scaling in edit label UI extension

examples/package.json, examples/webpack.config.js, packages/sprotty-elk/package.json, packages/sprotty-protocol/package.json, packages/sprotty/package.json, yarn.lock
When upgrading to TypeSript 5 and using `@inject` in a constructor the following error is raised:
```
Argument of type 'undefined' is not assignable to parameter of type 'string'
```
Upgrading to inversify 6 resolves the issue.
See this comment: https://github.com/microsoft/TypeScript/issues/52435#issuecomment-1405483291 and the following.
Related: https://github.com/eclipse-theia/theia/pull/12425
Inversify is now a `peerDependency` addressing: https://github.com/eclipse-sprotty/sprotty/issues/296
=> Bump TypeScript 5 and Inversify 6

packages/sprotty-protocol/src/utils/async.spec.ts, packages/sprotty-protocol/src/utils/async.ts
Keep track of the current promise state in a Deferred. Offers the possibility to query the current promise state via a sync property.
=> Track promise  state in Deferred

packages/sprotty/src/model-source/diagram-server.ts, packages/sprotty/src/model-source/local-model-source.ts, packages/sprotty/src/model-source/model-source.ts
I noticed quite often that the implementation of certain custom functionality requires access to the external model. This change makes the external model available in the `ModelSource` base class by exposing the `model` getter property. Also some code cleanup and commenting on the way.
=> Extracted `model` getter to abstract ModelSource

examples/random-graph/css/diagram.css, examples/random-graph/src/di.config.ts, examples/random-graph/src/standalone.ts, examples/random-graph/src/views.tsx, packages/sprotty/src/features/bounds/hidden-bounds-updater.ts, packages/sprotty/src/utils/browser.ts
Fixes #165.
I tried to find a generalization for the fix that would enable us to cover many use cases. The approach is to set a specific attribute to the SVG element that you'd like to use to determine the bounding box. Example:
https://github.com/eclipse-sprotty/sprotty/blob/9ff65633561a7c459e6e3662f0fabd45714f9182/examples/random-graph/src/views.tsx#L31-L40
I added ports with labels to the "Random Graph" example to show this.
Before the fix:
After the fix:
=> Fix computation of bounding box with children rendered outside

packages/sprotty/src/features/command-palette/command-palette.ts
Fix the position of the command palette suggestion box by setting the position to "fixed". This seems to be broken since the version bump form commander to version 7.0.1 (https://github.com/eclipse-sprotty/sprotty/pull/329).
Current Master:
This PR:
=> Fix command palette suggestion position

examples/random-graph/random-graph.html, examples/random-graph/src/di.config.ts, examples/random-graph/src/standalone.ts
Now the use can choose between Left/Right/Top/Down directions.
Another tweak demonstrates how to keep a selected node in place when the layout is changing. To test, select a node and change the layout direction. Selected node should remain in the same place.
=> Layout configuration for the random graph example

examples/multicore/src/chipmodel.ts, examples/svg/src/di.config.ts, examples/svg/src/standalone.ts, packages/sprotty-protocol/src/model.ts, packages/sprotty/src/base/commands/command.ts, packages/sprotty/src/features/bounds/views.spec.ts, packages/sprotty/src/features/projection/views.tsx, packages/sprotty/src/features/routing/views.spec.ts, packages/sprotty/src/features/update/update-model.ts, packages/sprotty/src/features/viewport/viewport-root.ts, packages/sprotty/src/features/viewport/viewport.spec.ts, packages/sprotty/src/graph/sgraph.ts, packages/sprotty/src/lib/svg-views.tsx
The following changes are for consistency with the new naming scheme:
- Renamed `ViewportRootElement` class to `ViewportRootElementImpl`
- Renamed `ViewportRootElementSchema` interface to `ViewportRootElement` and moved to `sprotty-protocol` package.
=> Renamed ViewportRootElement

packages/sprotty-protocol/src/actions.ts
Add an artificial property to the `RequestAction` definition to ensure that the generic type literal is not unused. This ensure that the TS compiler has all required type information and can implicitly derive the type of the Response action from a request action.
Fixes https://github.com/eclipse-sprotty/sprotty/issues/378
=> Fix typing of RequestActions

packages/sprotty-protocol/src/actions.ts, packages/sprotty/src/base/actions/action-dispatcher.ts
Fixes #384. Requests created in the client are always prefixed with `client_`. In addition, server code can use `setRequestContext('server')` to be 100% sure.
=> Add request context to avoid collisions in request IDs

configs/base.tsconfig.json, examples/package.json, lerna.json, package.json, packages/generator-sprotty/package.json, packages/sprotty-elk/package.json, packages/sprotty-protocol/package.json, packages/sprotty/package.json, yarn.lock
=> Updated project dependencies

packages/sprotty/src/features/bounds/abstract-layout.ts
Fixes #106
This fixes center alignment for when the parent node or the compartments parent has a set minWidth.
**How to test:**
Take the class diagram example 
configure the first node as follows (model-source.ts:155)
```
layout: 'vbox',
layoutOptions: {
minWidth: 200,
},
children: [
<SCompartment>{
id: 'node0_header',
type: 'comp:header',
layout: 'vbox',
layoutOptions: {
hAlign: 'center',
},
children: [
<SLabel>{
id: 'node0_classname',
type: 'label:heading',
text: 'Foo'
},
<SLabel>{
id: 'node0_classname_2',
type: 'label:heading',
text: 's'
},
]
```
you shouold now see both text items are aligned correctly in the center. Previous to this fix they would be aligned left even though hAlign center was set
=> fixed (w/h)Align center for containers with min width

examples/circlegraph/css/diagram.css, examples/classdiagram/css/diagram.css, examples/classdiagram/src/di.config.ts, examples/multicore/css/diagram.css, packages/sprotty/css/sprotty.css, packages/sprotty/src/base/views/view.spec.ts, packages/sprotty/src/base/views/view.tsx
Fixes #368
stopped missing view messages from overlapping;
messages now containing more relevant information; 
added warning to console
**How to test:**
using the class diagram example,
comment out: 
```
configureModelElement(context, 'routing-point', SRoutingHandleImpl, SRoutingHandleView);
configureModelElement(context, 'volatile-routing-point', SRoutingHandleImpl, SRoutingHandleView);
configureModelElement(context, 'bezier-create-routing-point', SRoutingHandleImpl, SBezierCreateHandleView);
configureModelElement(context, 'bezier-remove-routing-point', SRoutingHandleImpl, SBezierCreateHandleView);
configureModelElement(context, 'bezier-routing-point', SRoutingHandleImpl, SBezierControlHandleView);
```
after starting selecting an edge you should see the missing view messages not …
=> Better developer expereience for missing views

packages/sprotty/src/features/select/select.ts
Fixes #128
deselects selected nodes
even if the clicked element has no selectFeature enabled
=> Deselect nodes even if select feature of clicked is disabled

examples/package.json, examples/tsconfig.json, package.json, packages/generator-sprotty/package.json, packages/generator-sprotty/tsconfig.json, packages/sprotty-elk/package.json, packages/sprotty-elk/tsconfig.json, packages/sprotty-protocol/package.json, packages/sprotty-protocol/tsconfig.json, packages/sprotty/package.json, packages/sprotty/tsconfig.json, tsconfig.json, yarn.lock
`shx` is the command-line util of `shelljs` which is already a dependency of `yeoman-generator`
I just realized `rimraf` was updated again after a long pause. Now `shelljs` is moving slow, but there still seems to be activity.
=> Replace rimraf with shx

packages/sprotty-protocol/src/action-handler.ts, packages/sprotty-protocol/src/diagram-server.ts, packages/sprotty-protocol/src/diagram-services.ts, packages/sprotty-protocol/src/index.ts, packages/sprotty-protocol/src/utils/model-utils.ts
- Action handlers for the DiagramServer may return void.
- Added an optional index to the DiagramState (clients need to create it with their own strategy – doing it generically might be too costly).
=> Smaller improvements in sprotty-protocol

examples/classdiagram/src/di.config.ts, examples/classdiagram/src/model-source.ts, packages/sprotty-protocol/src/model.ts, packages/sprotty-protocol/src/utils/geometry.ts, packages/sprotty/src/features/edge-layout/edge-layout.ts, packages/sprotty/src/features/edge-layout/model.ts, packages/sprotty/src/features/routing/abstract-edge-router.ts, packages/sprotty/src/features/routing/routing.ts
This PR introduces a new configuration option for enhanced label positioning related to edges. It adds the possibility to move labels along the edge or completely free. Or set the moveMode to none to not move a certain label at all.
The move feature must be enabled in the di config for make label placement work.
For type-safe edge placement, the corresponding element type in the sprotty model must be extended with EdgeLayoutable type.
If edgePlacement is not specified, the label is placed at default position, with the exception that labels can be freely moved.
When edgePlacement is configured and moveMode is set to 'none', labels will not be moveable.
If edgePlacement is set and moveMode is 'edge', labels are constrained to movement along the associated edge. This also serves as the …
=> Move edge labels

examples/circlegraph/src/standalone.ts, packages/sprotty-protocol/src/actions.ts, packages/sprotty/src/base/animations/animation.ts, packages/sprotty/src/base/commands/command-stack.ts, packages/sprotty/src/base/commands/command.ts, packages/sprotty/src/features/move/move.ts
Commands that implement the new introduced IStoppableCommand do stop the last/current execution immediately to start another one of the same kind.
Solves https://github.com/eclipse-sprotty/sprotty/issues/1
It is nicely testable by raising the [duration time](https://github.com/jbicker/sprotty/blob/7d028502092be1533e60410cf824d83da8bcd4c7/packages/sprotty/src/base/di.config.ts#L86) of the CommandStackOptions and trigger the scrambling in the circle example multiple times.
=> Make command executions (e.g. animations) stoppable

examples/browser-app.ts, examples/flowchart/css/diagram.css, examples/flowchart/css/page.css, examples/flowchart/flowchart.html, examples/flowchart/src/data.ts, examples/flowchart/src/di.config.ts, examples/flowchart/src/model-source.ts, examples/flowchart/src/standalone.ts, examples/flowchart/src/views.tsx, examples/index.html
Adds an example for a flowchart diagram.
The main point of the example is to demonstrate custom views and in-place label editing.
Later on, this example could serve as a base to provide custom views for flowchart diagrams as a separate package.
=> Adds flowchart example

packages/sprotty/src/base/model/smodel-factory.ts, packages/sprotty/src/base/model/smodel-utils.ts, packages/sprotty/src/base/views/view.tsx, packages/sprotty/src/utils/registry.ts
Allow the element registration from the dependency injection to be overridden by another `ContainerModule`. This comes in handy when working with exported containers from the `sprotty-library` or when sharing  a `ContainerModule` when only a subset of model elements need a new registration.
This introduces a new helper function `overrideModelElement` to be used instead of `configureModelElement` in the `ContainerModule`
Example:
```
const moduleA = new ContainerModule((bind, unbind, isBound, rebind) => {
...
configureModelElement(context, 'myElementType', MyElementImplA, MyElementViewA);
}
const moduleB = new ContainerModule((bind, unbind, isBound, rebind) => {
...
overrideModelElement(context, 'myElementType', MyElementImplB, MyElementViewB);
}
const container = new Container(); …
```
=> Allow override of model element registration in DI

packages/sprotty-protocol/src/model.ts, packages/sprotty/src/features/bounds/abstract-layout.ts, packages/sprotty/src/features/bounds/hbox-layout.ts, packages/sprotty/src/features/bounds/layout-options.ts, packages/sprotty/src/features/bounds/stack-layout.ts, packages/sprotty/src/features/bounds/vbox-layout.ts
Improve the interfaces for elements layout and layout options to provide better content assist and autocompletion
=> Improve interfaces for layout and layout options

packages/sprotty/package.json, yarn.lock
- Exclude snabbdom 3.6.x since it causes problems for some users (closes #418)
- Revert a change made in #410 where inversify appears twice in package.json: `peerDependencies` and `dependencies`
=> Limit snabbdom to bugfix releases, remove inversify from dependencies

examples/browser-app.ts, examples/index.html, examples/jsxample/css/diagram.css, examples/jsxample/css/page.css, examples/jsxample/jsxample.html, examples/jsxample/src/di.config.ts, examples/jsxample/src/standalone.ts, examples/jsxample/src/views.tsx, packages/sprotty/src/lib/jsx.spec.tsx, packages/sprotty/src/lib/jsx.ts
Fixes https://github.com/eclipse-sprotty/sprotty/issues/419
It is now possible to add Function Components to the views as well as normal svg attributes to svg elements without adding 'attrs-' prefix.
A very simple example is added to demonstrate all cases.
=> Improved JSX factory

packages/sprotty/src/base/commands/command-stack-options.ts, packages/sprotty/src/base/di.config.ts, packages/sprotty/src/base/views/viewer-options.ts
This is analogous to `configureViewerOptions`.
=> Added configureCommandStackOptions utility

packages/sprotty/src/base/views/viewer-options.ts, packages/sprotty/src/base/views/viewer.tsx
Closes #425 
Adds an option in the `ViewerOptions` to add the id of the element that holds the shadow root.
The viewer will first check if this option is set before trying to retrieve the div container for the diagram.
=> Add supports for shadow DOM

examples/circlegraph/circlegraph.html, examples/classdiagram/class-diagram.html, examples/flowchart/flowchart.html, examples/index.html, examples/jsxample/jsxample.html, examples/multicore/multicore.html, examples/random-graph-distributed/random-graph.html, examples/random-graph/random-graph.html, examples/svg/svg-prerendered.html
After one of last changes of docs we forgot to correct the links to the interaction help page. This is corrected now.
=> Corrected help link in examples

examples/classdiagram/src/model-source.ts, packages/sprotty/src/features/move/move.ts
Fixes #428
The classdiagram example has been changed as well in order to demonstrate this case better.
=> Move also edge bendpoints of nested nodes when parent is moved 

examples/random-graph/random-graph.html, examples/random-graph/src/di.config.ts, examples/random-graph/src/standalone.ts, packages/sprotty/css/sprotty.css, packages/sprotty/src/features/edge-junction/di.config.ts, packages/sprotty/src/features/edge-junction/junction-finder.spec.ts, packages/sprotty/src/features/edge-junction/junction-finder.ts, packages/sprotty/src/features/edge-junction/junction-postprocessor.ts, packages/sprotty/src/features/routing/routing.ts, packages/sprotty/src/graph/views.tsx, packages/sprotty/src/index.ts
Solves #420 
Adds a new feature to find junction points on edges with the same source or target.
Similar to the `IntersectionFinder`, we provide a `ContainerModule` that can be loaded when needed in the inversify container.
The `JunctionFinder` ultimately sets the `isJunction` flag to `true` on `RoutingPoint`s where  a junction point must be drawn.
The rendering is done in the `PolylineEdgeView` (and therefore views that inherit this view) in a new function `renderFunctionPoints`.
They are represented as circles with a class `sprotty-junction` for easy styling.
=> Implement Junction Finder

examples/classdiagram/src/model-source.ts, packages/sprotty/src/features/move/move.ts
this is a followup for https://github.com/eclipse-sprotty/sprotty/pull/442
=> improved check for attached edges

packages/sprotty/src/features/edge-junction/di.config.ts, packages/sprotty/src/features/edge-junction/junction-postprocessor.ts, packages/sprotty/src/index.ts
Fixes #451 
The Junction point postprocessor was too greedy in selecting junction points groups from the DOM. It would also include groups from the hidden model, creating an issue with junction points disappearing when exporting the diagram to svg.
Now the postprocessor is also triggered on the hidden model, and the selectors are adapted to the hidden or base div.
During the first render (when a new model is set) the moved junction points are removed from the DOM.
=> Fix Junction points post processor

packages/sprotty/src/base/types.ts, packages/sprotty/src/features/export/export.ts, packages/sprotty/src/features/export/svg-export-postprocessor.ts, packages/sprotty/src/features/export/svg-exporter.ts, packages/sprotty/src/index.ts
Closes #421 
Adds the possibility to inject a SVG export postprocessor to manipulate the produced SVG element during an export.
Adds the possibility to skip the copying of styles on the exported SVG elements to improve performance.
Fix a bug with the exported viewport calculated on the wrong element.
=> SVG export postprocessor

packages/sprotty/src/features/edge-layout/edge-layout.ts, packages/sprotty/src/features/edge-layout/model.ts
There was a bug where edge labels that do not contain an `edgePlacement` property would be positioned incorrectly
=> Fix edge label placement

packages/sprotty/src/model-source/local-model-source.ts
Before setModel always ended up in UpdateModelAction which triggers (in that case) unwanted animations.
=> Use update boolean instead of hard set 'true' in modelsource submitModel

packages/sprotty/src/base/di.config.ts, packages/sprotty/src/base/types.ts, packages/sprotty/src/base/views/touch-tool.ts, packages/sprotty/src/features/viewport/di.config.ts, packages/sprotty/src/features/viewport/scroll.ts
Adds initial touch support
- `TouchTool` similar to `MouseTool`
- Touch support for canvas scroll / zoom
Open questions
- I did not yet add the `IMouseListener` as discussed in #462 
- If you want I can do so, however this would likely result in a breaking change, as I would need to change the signature of `MouseTool`
- I added no `decorate` method to `ITouchListener`, as if the `TouchTool` would call it an a class both extends `MouseListener` and `ITouchListener`, it would be called twice
- I could add it and only call it if the `ITouchListener` is not a `MouseListener`, however this sounds hacky
- I slightly changed the signature of some of the methods of `ScrollMouseListener` (e.g. `moveScrollBar`) to also accept a `Touch` as the event (as this provides the touch coordinates similar to …
=> Initial touch support

packages/generator-sprotty/sprotty-local-template/package.json
There is a conflict in the version of the package `reflect-metadata` in the generated `package.json` and the one expected by `inversify@6.2.2`. This would cause `npm install` to fail.
=> Update reflect-metadata version in generator-sprotty

packages/sprotty/src/base/di.config.ts, packages/sprotty/src/base/types.ts, packages/sprotty/src/base/views/pointer-tool.ts, packages/sprotty/src/base/views/touch-tool.ts, packages/sprotty/src/index.ts
First half of the implementation for #485 
- adds a `PointerTool`, similar to the already existing `MouseTool` and `TouchTool`
- fixes two small issues from by previous PR #475 
- renames two parameters for consistency (copy-paste error)
- exports the `TouchTool` via `index.ts` (I forgot last time, sry)
Regarding the second half of #485: this will require replacing sever `MouseListener`s with `PointerListener`s to do pointer capture, which is a breaking change.
I would recommend doing this with the next major release.
I can provide a PR now, or at any in the future based on your notice.
=> Pointer event support
